"""empty message

Revision ID: 5e458318cb1d
Revises: b35b68929f79
Create Date: 2021-01-29 19:04:37.824514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e458318cb1d'
down_revision = 'b35b68929f79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('home_page_actions', sa.Column('warning_message', sa.String(), nullable=True))
    op.add_column('search_actions', sa.Column('warning_message', sa.String(), nullable=True))
    op.add_column('view_actions', sa.Column('warning_message', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('view_actions', 'warning_message')
    op.drop_column('search_actions', 'warning_message')
    op.drop_column('home_page_actions', 'warning_message')
    # ### end Alembic commands ###
