"""empty message

Revision ID: b35b68929f79
Revises: d0072265c3be
Create Date: 2021-01-21 12:21:52.983676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b35b68929f79'
down_revision = 'd0072265c3be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('num_comments', sa.Integer(), nullable=True))
    op.add_column('videos', sa.Column('num_dislikes', sa.Integer(), nullable=True))
    op.add_column('videos', sa.Column('num_likes', sa.Integer(), nullable=True))
    op.add_column('videos', sa.Column('num_views', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'num_views')
    op.drop_column('videos', 'num_likes')
    op.drop_column('videos', 'num_dislikes')
    op.drop_column('videos', 'num_comments')
    # ### end Alembic commands ###
