"""empty message

Revision ID: be2599bce44e
Revises: cd3011dfb961
Create Date: 2021-01-16 11:42:50.292566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be2599bce44e'
down_revision = 'cd3011dfb961'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('search_actions', sa.Column('sequence_number', sa.Integer(), nullable=False))
    op.add_column('view_actions', sa.Column('sequence_number', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('view_actions', 'sequence_number')
    op.drop_column('search_actions', 'sequence_number')
    # ### end Alembic commands ###
