"""empty message

Revision ID: cd3011dfb961
Revises: 30f9328d7ee3
Create Date: 2021-01-07 13:43:08.704279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd3011dfb961'
down_revision = '30f9328d7ee3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('attributes', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('configurations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('bubble_create_strategy', sa.String(), nullable=True),
    sa.Column('bubble_burst_strategy', sa.String(), nullable=True),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # op.drop_constraint('bots_experiment_id_fkey', 'bots', type_='foreignkey')
    op.drop_column('bots', 'experiment_id')
    op.drop_table('experiments')
    op.add_column('bots', sa.Column('account_id', sa.Integer(), nullable=False))
    op.add_column('bots', sa.Column('configuration_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'bots', 'configurations', ['configuration_id'], ['id'])
    op.create_foreign_key(None, 'bots', 'accounts', ['account_id'], ['id'])
    op.drop_column('bots', 'account_username')
    op.add_column('seed_videos', sa.Column('stance', sa.String(), nullable=False))
    op.add_column('videos', sa.Column('youtube_id', sa.String(), nullable=False))
    op.drop_column('videos', 'url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('videos', 'youtube_id')
    op.drop_column('seed_videos', 'stance')
    op.add_column('bots', sa.Column('experiment_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('bots', sa.Column('account_username', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'bots', type_='foreignkey')
    op.drop_constraint(None, 'bots', type_='foreignkey')
    op.create_foreign_key('bots_experiment_id_fkey', 'bots', 'experiments', ['experiment_id'], ['id'])
    op.drop_column('bots', 'configuration_id')
    op.drop_column('bots', 'account_id')
    op.create_table('experiments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='experiments_pkey')
    )
    op.drop_table('configurations')
    op.drop_table('accounts')
    # ### end Alembic commands ###
