"""empty message

Revision ID: d0072265c3be
Revises: 11b0f401acae
Create Date: 2021-01-19 09:55:22.442166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0072265c3be'
down_revision = '11b0f401acae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channels', sa.Column('youtube_id', sa.String(), nullable=False))
    op.drop_column('channels', 'url')
    op.add_column('topics', sa.Column('full_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('topics', 'full_name')
    op.add_column('channels', sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('channels', 'youtube_id')
    # ### end Alembic commands ###
